language: go
go_import_path: github.com/zznop/sploit
git:
  depth: 1
env:
  - GO111MODULE=on
go: [1.13.x, 1.14.x]
os: [linux, osx]
script:
  - export GOMAXPROCS=4
  - export GORACE=halt_on_error=1
  - go test -v run TestNewELF
  - go test -v run TestELFBSS
  - go test -v run TestELFRead
  - go test -v run TestELFDumpROPGadgets
